// data/mockAuditData.ts
export const mockData = {
  id: 80,
  stages: [],
  assignments: [],
  audit_info: {
    id: 9,
    questions: [
      {
        id: 343,
        options: [],
        question_uuid: "auditgrp-q2",
        question: "Audited Location",
        description: null,
        critical: false,
        formula: null,
        question_type: "location",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: true,
        is_other: false,
        form: 80,
        stage: null,
        audit_info: 9,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-30T04:32:02.858694Z",
    updated_at: null,
    name: "Audit Info",
    form: 80,
  },
  audit_group: [
    {
      id: 11,
      questions: [
        {
          id: 344,
          options: [
            {
              id: 140,
              option: "opt1",
              score: 10,
              failed: false,
              order: 1,
            },
            {
              id: 141,
              option: "opt2",
              score: 20,
              failed: false,
              order: 2,
            },
            {
              id: 142,
              option: "opt3",
              score: 30,
              failed: false,
              order: 3,
            },
          ],
          question_uuid: "Group 1-q1",
          question: "what is your subject score",
          description: null,
          critical: false,
          formula: null,
          question_type: "audit",
          question_sub_type: null,
          question_hint: null,
          order: 1,
          is_required: true,
          require_live: false,
          number_of_file_allowed: null,
          min_value: null,
          max_value: null,
          max_score: null,
          is_logic_question: false,
          is_task_close_question: false,
          is_audit_info_question: false,
          is_other: false,
          form: 80,
          stage: null,
          audit_info: null,
          audit_group: 11,
          parent_question: null,
          sub_questions: [],
          logics: [
            {
              id: 41,
              logic_questions: [
                {
                  id: 345,
                  options: [],
                  created_at: "2025-07-30T04:32:04.364284Z",
                  updated_at: null,
                  question_uuid: "sub-q1753849506742-l2mkw1",
                  question: "congratulations please enter your name",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "short_answer",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: false,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: true,
                  is_task_close_question: false,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 80,
                  stage: null,
                  audit_info: null,
                  audit_group: 11,
                  parent_question: null,
                },
              ],
              created_at: "2025-07-30T04:32:04.240095Z",
              updated_at: null,
              logic_type: "is",
              logic_value: "opt3",
              notification: false,
              email: null,
              order: 1,
              user: null,
              group: null,
              form: 80,
              stage: null,
              audit_info: null,
              audit_group: 11,
              question: 344,
              follow_up: null,
            },
          ],
        },
        {
          id: 346,
          options: [
            {
              id: 137,
              created_at: "2025-07-30T04:32:05.546271Z",
              updated_at: null,
              option: "GTA",
              score: 0,
              failed: false,
              order: 1,
              question: 346,
              stage: null,
              audit_info: null,
              audit_group: 11,
              form: 80,
            },
            {
              id: 138,
              created_at: "2025-07-30T04:32:05.979464Z",
              updated_at: null,
              option: "IGI",
              score: 0,
              failed: false,
              order: 2,
              question: 346,
              stage: null,
              audit_info: null,
              audit_group: 11,
              form: 80,
            },
            {
              id: 139,
              created_at: "2025-07-30T04:32:06.414141Z",
              updated_at: null,
              option: "PUBG",
              score: 0,
              failed: false,
              order: 3,
              question: 346,
              stage: null,
              audit_info: null,
              audit_group: 11,
              form: 80,
            },
          ],
          question_uuid: "q1753849578228-6n09t5",
          question: "please select your fav game",
          description: null,
          critical: false,
          formula: null,
          question_type: "dropdown",
          question_sub_type: null,
          question_hint: null,
          order: 2,
          is_required: false,
          require_live: false,
          number_of_file_allowed: null,
          min_value: null,
          max_value: null,
          max_score: null,
          is_logic_question: false,
          is_task_close_question: false,
          is_audit_info_question: false,
          is_other: false,
          form: 80,
          stage: null,
          audit_info: null,
          audit_group: 11,
          parent_question: null,
          sub_questions: [],
          logics: [
            {
              id: 42,
              logic_questions: [
                {
                  id: 347,
                  options: [],
                  created_at: "2025-07-30T04:32:06.727129Z",
                  updated_at: null,
                  question_uuid: "sub-q1753849649114-w3as6y",
                  question: "HOW MUCH YOU SPENT TO GET THE GAME",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "short_answer",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: false,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: true,
                  is_task_close_question: false,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 80,
                  stage: null,
                  audit_info: null,
                  audit_group: 11,
                  parent_question: null,
                },
              ],
              created_at: "2025-07-30T04:32:06.602527Z",
              updated_at: null,
              logic_type: "is",
              logic_value: "GTA",
              notification: false,
              email: null,
              order: 1,
              user: null,
              group: null,
              form: 80,
              stage: null,
              audit_info: null,
              audit_group: 11,
              question: 346,
              follow_up: null,
            },
            {
              id: 43,
              logic_questions: [
                {
                  id: 348,
                  options: [],
                  created_at: "2025-07-30T04:32:07.221788Z",
                  updated_at: null,
                  question_uuid: "sub-q1753849668154-689a6n",
                  question: "IS ITS GOOD TO PLAY ?",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "short_answer",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: false,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: true,
                  is_task_close_question: false,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 80,
                  stage: null,
                  audit_info: null,
                  audit_group: 11,
                  parent_question: null,
                },
              ],
              created_at: "2025-07-30T04:32:07.097823Z",
              updated_at: null,
              logic_type: "is",
              logic_value: "IGI",
              notification: false,
              email: null,
              order: 1,
              user: null,
              group: null,
              form: 80,
              stage: null,
              audit_info: null,
              audit_group: 11,
              question: 346,
              follow_up: null,
            },
          ],
        },
      ],
      created_at: "2025-07-30T04:32:03.801112Z",
      updated_at: null,
      name: "audit question",
      form: 80,
      pass_percentage: 70,
    },
  ],
  created_at: "2025-07-30T04:32:02.608438Z",
  updated_at: null,
  form_type: "audit",
  title: "test audit form",
  prefix: "",
  GPS: false,
  share_reponse: false,
  allow_editing: false,
  can_edit_previos_state: false,
  auto_share_reponse: false,
  pass_percentage: 70,
  max_score: 100,
  is_deleted: false,
  is_archived: false,
  last_deleted_date: null,
  last_archived_date: null,
  created_by: 85,
  updated_by: null,
  organization: 13,
  folder: 31,
  form_admin: 25,
  deletedBy: null,
  archivedBy: null,
};
