// data/mockAuditData.ts
export const mockData = {
  id: 80,
  stages: [],
  assignments: [],
  audit_info: {
    id: 9,
    questions: [
      {
        id: 343,
        options: [],
        question_uuid: "auditgrp-q2",
        question: "Audited Location",
        description: null,
        critical: false,
        formula: null,
        question_type: "location",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: true,
        is_other: false,
        form: 80,
        stage: null,
        audit_info: 9,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-30T04:32:02.858694Z",
    updated_at: null,
    name: "Audit Info",
    form: 80,
  },
  audit_group: [
    {
      id: 11,
      questions: [
        {
          id: 344,
          options: [
            {
              id: 140,
              option: "opt1",
              score: 10,
              failed: false,
              order: 1,
            },
            {
              id: 141,
              option: "opt2",
              score: 20,
              failed: false,
              order: 2,
            },
            {
              id: 142,
              option: "opt3",
              score: 30,
              failed: false,
              order: 3,
            },
          ],
          question_uuid: "Group 1-q1",
          question: "what is your subject score",
          description: null,
          critical: false,
          formula: null,
          question_type: "audit",
          question_sub_type: null,
          question_hint: null,
          order: 1,
          is_required: true,
          require_live: false,
          number_of_file_allowed: null,
          min_value: null,
          max_value: null,
          max_score: null,
          is_logic_question: false,
          is_task_close_question: false,
          is_audit_info_question: false,
          is_other: false,
          form: 80,
          stage: null,
          audit_info: null,
          audit_group: 11,
          parent_question: null,
          sub_questions: [],
          logics: [
            {
              id: 41,
              logic_questions: [
                {
                  id: 345,
                  options: [],
                  created_at: "2025-07-30T04:32:04.364284Z",
                  updated_at: null,
                  question_uuid: "sub-q1753849506742-l2mkw1",
                  question: "congratulations please enter your name",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "short_answer",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: false,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: true,
                  is_task_close_question: false,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 80,
                  stage: null,
                  audit_info: null,
                  audit_group: 11,
                  parent_question: null,
                },
              ],
              created_at: "2025-07-30T04:32:04.240095Z",
              updated_at: null,
              logic_type: "is",
              logic_value: "opt3",
              notification: false,
              email: null,
              order: 1,
              user: null,
              group: null,
              form: 80,
              stage: null,
              audit_info: null,
              audit_group: 11,
              question: 344,
              follow_up: null,
            },
          ],
        },
        {
          id: 346,
          options: [
            {
              id: 137,
              created_at: "2025-07-30T04:32:05.546271Z",
              updated_at: null,
              option: "GTA",
              score: 0,
              failed: false,
              order: 1,
              question: 346,
              stage: null,
              audit_info: null,
              audit_group: 11,
              form: 80,
            },
            {
              id: 138,
              created_at: "2025-07-30T04:32:05.979464Z",
              updated_at: null,
              option: "IGI",
              score: 0,
            failed: false,
              order: 2,
              question: 346,
              stage: null,
              audit_info: null,
              audit_group: 11,
              form: 80,
            },
            {
              id: 139,
              created_at: "2025-07-30T04:32:06.414141Z",
              updated_at: null,
              option: "PUBG",
              score: 0,
              failed: false,
              order: 3,
              question: 346,
              stage: null,
              audit_info: null,
              audit_group: 11,
              form: 80,
            },
          ],
          question_uuid: "q1753849578228-6n09t5",
          question: "please select your fav game",
          description: null,
          critical: false,
          formula: null,
          question_type: "dropdown",
          question_sub_type: null,
          question_hint: null,
          order: 2,
          is_required: false,
          require_live: false,
          number_of_file_allowed: null,
          min_value: null,
          max_value: null,
          max_score: null,
          is_logic_question: false,
          is_task_close_question: false,
          is_audit_info_question: false,
          is_other: false,
          form: 80,
          stage: null,
          audit_info: null,
          audit_group: 11,
          parent_question: null,
          sub_questions: [],
          logics: [
            {
              id: 42,
              logic_questions: [
                {
                  id: 347,
                  options: [],
                  created_at: "2025-07-30T04:32:06.727129Z",
                  updated_at: null,
                  question_uuid: "sub-q1753849649114-w3as6y",
                  question: "HOW MUCH YOU SPENT TO GET THE GAME",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "short_answer",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: false,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: true,
                  is_task_close_question: false,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 80,
                  stage: null,
                  audit_info: null,
                  audit_group: 11,
                  parent_question: null,
                },
              ],
              created_at: "2025-07-30T04:32:06.602527Z",
              updated_at: null,
              logic_type: "is",
              logic_value: "GTA",
              notification: false,
              email: null,
              order: 1,
              user: null,
              group: null,
              form: 80,
              stage: null,
              audit_info: null,
              audit_group: 11,
              question: 346,
              follow_up: null,
            },
            {
              id: 43,
              logic_questions: [
                {
                  id: 348,
                  options: [],
                  created_at: "2025-07-30T04:32:07.221788Z",
                  updated_at: null,
                  question_uuid: "sub-q1753849668154-689a6n",
                  question: "IS ITS GOOD TO PLAY ?",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "short_answer",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: false,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: true,
                  is_task_close_question: false,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 80,
                  stage: null,
                  audit_info: null,
                  audit_group: 11,
                  parent_question: null,
                },
              ],
              created_at: "2025-07-30T04:32:07.097823Z",
              updated_at: null,
              logic_type: "is",
              logic_value: "IGI",
              notification: false,
              email: null,
              order: 1,
              user: null,
              group: null,
              form: 80,
              stage: null,
              audit_info: null,
              audit_group: 11,
              question: 346,
              follow_up: null,
            },
          ],
        },
      ],
      created_at: "2025-07-30T04:32:03.801112Z",
      updated_at: null,
      name: "audit question",
      form: 80,
      pass_percentage: 70,
    },
  ],
  created_at: "2025-07-30T04:32:02.608438Z",
  updated_at: null,
  form_type: "audit",
  title: "test audit form",
  prefix: "",
  GPS: false,
  share_reponse: false,
  allow_editing: false,
  can_edit_previos_state: false,
  auto_share_reponse: false,
  pass_percentage: 70,
  max_score: 100,
  is_deleted: false,
  is_archived: false,
  last_deleted_date: null,
  last_archived_date: null,
  created_by: 85,
  updated_by: null,
  organization: 13,
  folder: 31,
  form_admin: 25,
  deletedBy: null,
  archivedBy: null,
};


// // data/mockAuditData.ts
// export const mockData = {
//   "id": 148,
//   "stages": [],
//   "audit_info": {
//     "id": 7,
//     "questions": [
//       {
//         "id": 1333,
//         "options": [],
//         "question_uuid": "uuid1",
//         "question": "Audit Info 1 - question 1",
//         "description": null,
//         "critical": false,
//         "formula": null,
//         "question_type": "division",
//         "question_sub_type": null,
//         "question_hint": null,
//         "order": 1,
//         "is_required": true,
//         "require_live": false,
//         "number_of_file_allowed": null,
//         "min_value": 1,
//         "max_value": 2,
//         "max_score": null,
//         "is_logic_question": false,
//         "is_task_close_question": false,
//         "is_audit_info_question": true,
//         "is_other": false,
//         "form": 148,
//         "stage": null,
//         "audit_info": 7,
//         "audit_group": null,
//         "parent_question": null,
//         "sub_questions": [],
//         "logics": [
//           {
//             "id": 222,
//             "logic_questions": [
//               {
//                 "id": 1334,
//                 "options": [],
//                 "created_at": "2025-08-07T11:16:53.369914Z",
//                 "updated_at": null,
//                 "question_uuid": "question_uuid72",
//                 "question": "Logic 1 question 1",
//                 "description": null,
//                 "critical": false,
//                 "formula": null,
//                 "question_type": "division",
//                 "question_sub_type": null,
//                 "question_hint": null,
//                 "order": 1,
//                 "is_required": true,
//                 "require_live": false,
//                 "number_of_file_allowed": null,
//                 "min_value": 1,
//                 "max_value": 2,
//                 "max_score": null,
//                 "is_logic_question": true,
//                 "is_task_close_question": false,
//                 "is_audit_info_question": false,
//                 "is_other": false,
//                 "form": 148,
//                 "stage": null,
//                 "audit_info": 7,
//                 "audit_group": null,
//                 "parent_question": null
//               },
//               {
//                 "id": 1335,
//                 "options": [],
//                 "created_at": "2025-08-07T11:16:53.393828Z",
//                 "updated_at": null,
//                 "question_uuid": "question_uuid75",
//                 "question": "Logic 1 question 2",
//                 "description": null,
//                 "critical": false,
//                 "formula": null,
//                 "question_type": "division",
//                 "question_sub_type": null,
//                 "question_hint": null,
//                 "order": 2,
//                 "is_required": true,
//                 "require_live": false,
//                 "number_of_file_allowed": null,
//                 "min_value": 1,
//                 "max_value": 2,
//                 "max_score": null,
//                 "is_logic_question": true,
//                 "is_task_close_question": false,
//                 "is_audit_info_question": false,
//                 "is_other": false,
//                 "form": 148,
//                 "stage": null,
//                 "audit_info": 7,
//                 "audit_group": null,
//                 "parent_question": null
//               }
//             ],
//             "created_at": "2025-08-07T11:16:53.337001Z",
//             "updated_at": null,
//             "logic_type": "is",
//             "comparison": null,
//             "logic_value": "YES",
//             "notification": false,
//             "email": null,
//             "order": 1,
//             "user": null,
//             "group": null,
//             "form": 148,
//             "stage": null,
//             "audit_info": 7,
//             "audit_group": null,
//             "question": 1333,
//             "follow_up": {
//               "task_close_questions": [
//                 {
//                   "id": 1336,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:53.419151Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid78",
//                   "question": "Audit Info 1 - question 1 - Followup 1 - UP TASK CLOSE QUESTION 1",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "date",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 1,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": null,
//                   "max_value": null,
//                   "max_score": null,
//                   "is_logic_question": false,
//                   "is_task_close_question": true,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": 7,
//                   "audit_group": null,
//                   "parent_question": null
//                 },
//                 {
//                   "id": 1337,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:53.431405Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid58",
//                   "question": "Audit Info 1 - question 1 - Followup 1 - UP TASK CLOSE QUESTION 2",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "time",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 2,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": null,
//                   "max_value": null,
//                   "max_score": null,
//                   "is_logic_question": false,
//                   "is_task_close_question": true,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": 7,
//                   "audit_group": null,
//                   "parent_question": null
//                 }
//               ],
//               "title": "Audit Info 1 - question 1 - LOGIC 1 - Followup 1",
//               "deadline": 30,
//               "assign_to": "form_submitter",
//               "logic": 222,
//               "assign_form": null,
//               "user": null,
//               "group": null,
//               "form": 148,
//               "stage": null,
//               "audit_info": 7,
//               "audit_group": null,
//               "question": 1333
//             }
//           }
//         ]
//       },
//       {
//         "id": 1338,
//         "options": [
//           {
//             "id": 530,
//             "created_at": "2025-08-07T11:16:53.466330Z",
//             "updated_at": null,
//             "option": "Audit Info 1 - question 2 - Option 1",
//             "score": 20,
//             "failed": true,
//             "order": 1,
//             "question": 1338,
//             "stage": null,
//             "audit_info": 7,
//             "audit_group": null,
//             "form": 148
//           },
//           {
//             "id": 531,
//             "created_at": "2025-08-07T11:16:53.488562Z",
//             "updated_at": null,
//             "option": "Audit Info 1 - question 2 - Option 2",
//             "score": 20,
//             "failed": false,
//             "order": 2,
//             "question": 1338,
//             "stage": null,
//             "audit_info": 7,
//             "audit_group": null,
//             "form": 148
//           },
//           {
//             "id": 532,
//             "created_at": "2025-08-07T11:16:53.694266Z",
//             "updated_at": null,
//             "option": "Audit Info 1 - question 2 - Option 3",
//             "score": 40,
//             "failed": false,
//             "order": 3,
//             "question": 1338,
//             "stage": null,
//             "audit_info": 7,
//             "audit_group": null,
//             "form": 148
//           }
//         ],
//         "question_uuid": "uuid2",
//         "question": "Audit Info 1 - question 2",
//         "description": null,
//         "critical": true,
//         "formula": null,
//         "question_type": "audit",
//         "question_sub_type": null,
//         "question_hint": null,
//         "order": 2,
//         "is_required": true,
//         "require_live": false,
//         "number_of_file_allowed": null,
//         "min_value": null,
//         "max_value": null,
//         "max_score": 40,
//         "is_logic_question": false,
//         "is_task_close_question": false,
//         "is_audit_info_question": true,
//         "is_other": true,
//         "form": 148,
//         "stage": null,
//         "audit_info": 7,
//         "audit_group": null,
//         "parent_question": null,
//         "sub_questions": [],
//         "logics": []
//       }
//     ],
//     "created_at": "2025-08-07T11:16:53.289687Z",
//     "updated_at": null,
//     "name": "Audit Info 1",
//     "form": 148
//   },
//   "audit_group": [
//     {
//       "id": 12,
//       "questions": [
//         {
//           "id": 1339,
//           "options": [],
//           "question_uuid": "question_uuid12",
//           "question": "Audit Group 1 - Question 1",
//           "description": null,
//           "critical": false,
//           "formula": null,
//           "question_type": "long_answer",
//           "question_sub_type": null,
//           "question_hint": "Question Hint",
//           "order": 1,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": null,
//           "max_value": null,
//           "max_score": null,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": false,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 12,
//           "parent_question": null,
//           "sub_questions": [],
//           "logics": [
//             {
//               "id": 223,
//               "logic_questions": [
//                 {
//                   "id": 1340,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:53.784692Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid720",
//                   "question": "Audit Group 1 - Question 1 - Logic 1 - question 1",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 1,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 12,
//                   "parent_question": null
//                 },
//                 {
//                   "id": 1341,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:53.792696Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid750",
//                   "question": "Audit Group 1 - Question 1 - Logic 1 - question 2",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 2,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 12,
//                   "parent_question": null
//                 }
//               ],
//               "created_at": "2025-08-07T11:16:53.779697Z",
//               "updated_at": null,
//               "logic_type": "is",
//               "comparison": null,
//               "logic_value": "YES",
//               "notification": false,
//               "email": null,
//               "order": 1,
//               "user": null,
//               "group": null,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 12,
//               "question": 1339,
//               "follow_up": {
//                 "task_close_questions": [
//                   {
//                     "id": 1342,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:53.804211Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid780",
//                     "question": "Audit Group 1 - question 1 - LOGIC 1 - Followup 1 - UP TASK CLOSE QUESTION 1",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "date",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 1,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 12,
//                     "parent_question": null
//                   },
//                   {
//                     "id": 1343,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:53.811413Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid580",
//                     "question": "Audit Group 1 - question 1 - LOGIC 1 - Followup 1 - UP TASK CLOSE QUESTION 2",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "time",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 2,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 12,
//                     "parent_question": null
//                   }
//                 ],
//                 "title": "Audit Group 1 - question 1 - LOGIC 1 - Followup 1",
//                 "deadline": 30,
//                 "assign_to": "form_submitter",
//                 "logic": 223,
//                 "assign_form": null,
//                 "user": null,
//                 "group": null,
//                 "form": 148,
//                 "stage": null,
//                 "audit_info": null,
//                 "audit_group": 12,
//                 "question": 1339
//               }
//             },
//             {
//               "id": 224,
//               "logic_questions": [
//                 {
//                   "id": 1344,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:53.832193Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid721",
//                   "question": "Audit Group 1 - Question 1 - Logic 2 - question 1",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 1,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 12,
//                   "parent_question": null
//                 },
//                 {
//                   "id": 1345,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:53.840870Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid751",
//                   "question": "Audit Group 1 - Question 1 - Logic 2 - question 2",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 2,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 12,
//                   "parent_question": null
//                 }
//               ],
//               "created_at": "2025-08-07T11:16:53.828191Z",
//               "updated_at": null,
//               "logic_type": "is",
//               "comparison": null,
//               "logic_value": "NO",
//               "notification": false,
//               "email": null,
//               "order": 1,
//               "user": null,
//               "group": null,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 12,
//               "question": 1339,
//               "follow_up": {
//                 "task_close_questions": [
//                   {
//                     "id": 1346,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:53.855424Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid781",
//                     "question": "Audit Group 1 - question 1 - LOGIC 2 - Followup 1 - UP TASK CLOSE QUESTION 1",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "date",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 1,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 12,
//                     "parent_question": null
//                   },
//                   {
//                     "id": 1347,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:53.861993Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid581",
//                     "question": "Audit Group 1 - question 1 - LOGIC 2 - Followup 1 - UP TASK CLOSE QUESTION 2",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "time",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 2,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 12,
//                     "parent_question": null
//                   }
//                 ],
//                 "title": "Audit Group 1 - question 1 - LOGIC 2 - Followup 1",
//                 "deadline": 30,
//                 "assign_to": "form_submitter",
//                 "logic": 224,
//                 "assign_form": null,
//                 "user": null,
//                 "group": null,
//                 "form": 148,
//                 "stage": null,
//                 "audit_info": null,
//                 "audit_group": 12,
//                 "question": 1339
//               }
//             }
//           ]
//         },
//         {
//           "id": 1348,
//           "options": [
//             {
//               "id": 533,
//               "created_at": "2025-08-07T11:16:53.887776Z",
//               "updated_at": null,
//               "option": "Audit Group 1 - question 2 - Option 1",
//               "score": 20,
//               "failed": false,
//               "order": 1,
//               "question": 1348,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 12,
//               "form": 148
//             },
//             {
//               "id": 534,
//               "created_at": "2025-08-07T11:16:53.898276Z",
//               "updated_at": null,
//               "option": "Audit Group 1 - question 2 - Option 2",
//               "score": 20,
//               "failed": false,
//               "order": 2,
//               "question": 1348,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 12,
//               "form": 148
//             },
//             {
//               "id": 535,
//               "created_at": "2025-08-07T11:16:53.910885Z",
//               "updated_at": null,
//               "option": "Audit Group 1 - question 2 - Option 3",
//               "score": 40,
//               "failed": false,
//               "order": 3,
//               "question": 1348,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 12,
//               "form": 148
//             }
//           ],
//           "question_uuid": "uuid2",
//           "question": "Audit Group 1 - question 2",
//           "description": null,
//           "critical": false,
//           "formula": null,
//           "question_type": "audit",
//           "question_sub_type": null,
//           "question_hint": null,
//           "order": 2,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": null,
//           "max_value": null,
//           "max_score": 40,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": true,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 12,
//           "parent_question": null,
//           "sub_questions": [],
//           "logics": []
//         },
//         {
//           "id": 1349,
//           "options": [],
//           "question_uuid": "question_uuid31",
//           "question": "Audit Group 1- Question 3",
//           "description": null,
//           "critical": false,
//           "formula": "SUM(question_uuid01+question_uuid25)*question_uuid04",
//           "question_type": "formula",
//           "question_sub_type": null,
//           "question_hint": null,
//           "order": 3,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": null,
//           "max_value": null,
//           "max_score": null,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": false,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 12,
//           "parent_question": null,
//           "sub_questions": [],
//           "logics": []
//         }
//       ],
//       "created_at": "2025-08-07T11:16:53.730349Z",
//       "updated_at": null,
//       "name": "Audit Group 1",
//       "form": 148
//     },
//     {
//       "id": 13,
//       "questions": [
//         {
//           "id": 1350,
//           "options": [],
//           "question_uuid": "question_uuid12",
//           "question": "Audit Group 2 - Question 1",
//           "description": null,
//           "critical": false,
//           "formula": null,
//           "question_type": "long_answer",
//           "question_sub_type": null,
//           "question_hint": "Question Hint",
//           "order": 1,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": null,
//           "max_value": null,
//           "max_score": null,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": false,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 13,
//           "parent_question": null,
//           "sub_questions": [],
//           "logics": []
//         },
//         {
//           "id": 1351,
//           "options": [
//             {
//               "id": 536,
//               "created_at": "2025-08-07T11:16:54.013776Z",
//               "updated_at": null,
//               "option": "Audit Group 2 - question 2 - Option 1",
//               "score": 20,
//               "failed": false,
//               "order": 1,
//               "question": 1351,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 13,
//               "form": 148
//             },
//             {
//               "id": 537,
//               "created_at": "2025-08-07T11:16:54.026748Z",
//               "updated_at": null,
//               "option": "Audit Group 2 - question 2 - Option 2",
//               "score": 20,
//               "failed": false,
//               "order": 2,
//               "question": 1351,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 13,
//               "form": 148
//             },
//             {
//               "id": 538,
//               "created_at": "2025-08-07T11:16:54.039880Z",
//               "updated_at": null,
//               "option": "Audit Group 2 - question 2 - Option 3",
//               "score": 40,
//               "failed": false,
//               "order": 3,
//               "question": 1351,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 13,
//               "form": 148
//             }
//           ],
//           "question_uuid": "uuid2",
//           "question": "Audit Group 2 - Question 2",
//           "description": null,
//           "critical": false,
//           "formula": null,
//           "question_type": "audit",
//           "question_sub_type": null,
//           "question_hint": null,
//           "order": 2,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": null,
//           "max_value": null,
//           "max_score": 40,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": true,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 13,
//           "parent_question": null,
//           "sub_questions": [],
//           "logics": [
//             {
//               "id": 225,
//               "logic_questions": [
//                 {
//                   "id": 1352,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:54.059708Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid720",
//                   "question": "Audit Group 2 - Question 2 - Logic 1 - question 1",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 1,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 13,
//                   "parent_question": null
//                 },
//                 {
//                   "id": 1353,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:54.065707Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid750",
//                   "question": "Audit Group 2 - Question 2 - Logic 1 - question 2",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 2,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 13,
//                   "parent_question": null
//                 }
//               ],
//               "created_at": "2025-08-07T11:16:54.053459Z",
//               "updated_at": null,
//               "logic_type": "is",
//               "comparison": null,
//               "logic_value": "NO",
//               "notification": false,
//               "email": null,
//               "order": 1,
//               "user": null,
//               "group": null,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 13,
//               "question": 1351,
//               "follow_up": {
//                 "task_close_questions": [
//                   {
//                     "id": 1354,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:54.080526Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid780",
//                     "question": "Audit Group 2 - Question 2 - LOGIC 1 - Followup 1 - UP TASK CLOSE QUESTION 1",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "date",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 1,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 13,
//                     "parent_question": null
//                   },
//                   {
//                     "id": 1355,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:54.085046Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid580",
//                     "question": "Audit Group 2 - Question 2 - LOGIC 1 - Followup 1 - UP TASK CLOSE QUESTION 2",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "time",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 2,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 13,
//                     "parent_question": null
//                   }
//                 ],
//                 "title": "Audit Group 2 - Question 2 - LOGIC 1 - Followup 1",
//                 "deadline": 30,
//                 "assign_to": "form_submitter",
//                 "logic": 225,
//                 "assign_form": null,
//                 "user": null,
//                 "group": null,
//                 "form": 148,
//                 "stage": null,
//                 "audit_info": null,
//                 "audit_group": 13,
//                 "question": 1351
//               }
//             },
//             {
//               "id": 226,
//               "logic_questions": [
//                 {
//                   "id": 1356,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:54.105267Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid721",
//                   "question": "Audit Group 2 - Question 2 - Logic 2 - question 1",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 1,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 13,
//                   "parent_question": null
//                 },
//                 {
//                   "id": 1357,
//                   "options": [],
//                   "created_at": "2025-08-07T11:16:54.112451Z",
//                   "updated_at": null,
//                   "question_uuid": "question_uuid751",
//                   "question": "Audit Group 2 - Question 2 - Logic 2 - question 2",
//                   "description": null,
//                   "critical": false,
//                   "formula": null,
//                   "question_type": "division",
//                   "question_sub_type": null,
//                   "question_hint": null,
//                   "order": 2,
//                   "is_required": true,
//                   "require_live": false,
//                   "number_of_file_allowed": null,
//                   "min_value": 1,
//                   "max_value": 2,
//                   "max_score": null,
//                   "is_logic_question": true,
//                   "is_task_close_question": false,
//                   "is_audit_info_question": false,
//                   "is_other": false,
//                   "form": 148,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 13,
//                   "parent_question": null
//                 }
//               ],
//               "created_at": "2025-08-07T11:16:54.100261Z",
//               "updated_at": null,
//               "logic_type": "is",
//               "comparison": null,
//               "logic_value": "YES",
//               "notification": false,
//               "email": null,
//               "order": 1,
//               "user": null,
//               "group": null,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 13,
//               "question": 1351,
//               "follow_up": {
//                 "task_close_questions": [
//                   {
//                     "id": 1358,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:54.123447Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid781",
//                     "question": "Audit Group 2 - Question 2 - LOGIC 2 - Followup 1 - UP TASK CLOSE QUESTION 1",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "date",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 1,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 13,
//                     "parent_question": null
//                   },
//                   {
//                     "id": 1359,
//                     "options": [],
//                     "created_at": "2025-08-07T11:16:54.128930Z",
//                     "updated_at": null,
//                     "question_uuid": "question_uuid581",
//                     "question": "Audit Group 2 - Question 2 - LOGIC 2 - Followup 1 - UP TASK CLOSE QUESTION 2",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "time",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 2,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": true,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 148,
//                     "stage": null,
//                     "audit_info": null,
//                     "audit_group": 13,
//                     "parent_question": null
//                   }
//                 ],
//                 "title": "Audit Group 2 - Question 2 - LOGIC 2 - Followup 1",
//                 "deadline": 30,
//                 "assign_to": "form_submitter",
//                 "logic": 226,
//                 "assign_form": null,
//                 "user": null,
//                 "group": null,
//                 "form": 148,
//                 "stage": null,
//                 "audit_info": null,
//                 "audit_group": 13,
//                 "question": 1351
//               }
//             }
//           ]
//         },
//         {
//           "id": 1360,
//           "options": [],
//           "question_uuid": "question_uuid31",
//           "question": "Audit Group 2 - Question 3",
//           "description": null,
//           "critical": false,
//           "formula": "SUM(question_uuid01+question_uuid25)*question_uuid04",
//           "question_type": "formula",
//           "question_sub_type": null,
//           "question_hint": null,
//           "order": 3,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": null,
//           "max_value": null,
//           "max_score": null,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": false,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 13,
//           "parent_question": null,
//           "sub_questions": [],
//           "logics": []
//         }
//       ],
//       "created_at": "2025-08-07T11:16:53.962093Z",
//       "updated_at": null,
//       "name": "Audit Group 2",
//       "form": 148
//     },
//     {
//       "id": 14,
//       "questions": [
//         {
//           "id": 1361,
//           "options": [],
//           "question_uuid": "question_uuid56",
//           "question": "Audit Group 3 - Question 1",
//           "description": null,
//           "critical": false,
//           "formula": null,
//           "question_type": "table",
//           "question_sub_type": null,
//           "question_hint": null,
//           "order": 1,
//           "is_required": true,
//           "require_live": false,
//           "number_of_file_allowed": null,
//           "min_value": 1,
//           "max_value": 2,
//           "max_score": null,
//           "is_logic_question": false,
//           "is_task_close_question": false,
//           "is_audit_info_question": false,
//           "is_other": false,
//           "form": 148,
//           "stage": null,
//           "audit_info": null,
//           "audit_group": 14,
//           "parent_question": null,
//           "sub_questions": [
//             {
//               "id": 1362,
//               "options": [],
//               "question_uuid": "question_uuid57",
//               "question": "Audit Group 3 - Question 1 - Child Question 1",
//               "description": null,
//               "critical": false,
//               "formula": null,
//               "question_type": "location",
//               "question_sub_type": null,
//               "question_hint": null,
//               "order": 1,
//               "is_required": true,
//               "require_live": false,
//               "number_of_file_allowed": null,
//               "min_value": null,
//               "max_value": null,
//               "max_score": null,
//               "is_logic_question": false,
//               "is_task_close_question": false,
//               "is_audit_info_question": false,
//               "is_other": false,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 14,
//               "parent_question": 1361,
//               "sub_questions": [],
//               "logics": []
//             },
//             {
//               "id": 1363,
//               "options": [],
//               "question_uuid": "question_uuid58",
//               "question": "Audit Group 3 - Question 1 - Child Question 2",
//               "description": null,
//               "critical": false,
//               "formula": null,
//               "question_type": "division",
//               "question_sub_type": null,
//               "question_hint": null,
//               "order": 2,
//               "is_required": true,
//               "require_live": false,
//               "number_of_file_allowed": null,
//               "min_value": null,
//               "max_value": null,
//               "max_score": null,
//               "is_logic_question": false,
//               "is_task_close_question": false,
//               "is_audit_info_question": false,
//               "is_other": false,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 14,
//               "parent_question": 1361,
//               "sub_questions": [],
//               "logics": []
//             },
//             {
//               "id": 1364,
//               "options": [
//                 {
//                   "id": 539,
//                   "created_at": "2025-08-07T11:16:54.195195Z",
//                   "updated_at": null,
//                   "option": "Audit Group 3 - Question 1 - Child Question 3 - Option 1",
//                   "score": 0,
//                   "failed": false,
//                   "order": 1,
//                   "question": 1364,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 14,
//                   "form": 148
//                 },
//                 {
//                   "id": 540,
//                   "created_at": "2025-08-07T11:16:54.207561Z",
//                   "updated_at": null,
//                   "option": "Audit Group 3 - Question 1 - Child Question 3 - Option 2",
//                   "score": 0,
//                   "failed": false,
//                   "order": 2,
//                   "question": 1364,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 14,
//                   "form": 148
//                 },
//                 {
//                   "id": 541,
//                   "created_at": "2025-08-07T11:16:54.218570Z",
//                   "updated_at": null,
//                   "option": "Audit Group 3 - Question 1 - Child Question 3 - Option 3",
//                   "score": 0,
//                   "failed": false,
//                   "order": 3,
//                   "question": 1364,
//                   "stage": null,
//                   "audit_info": null,
//                   "audit_group": 14,
//                   "form": 148
//                 }
//               ],
//               "question_uuid": "question_uuid59",
//               "question": "Audit Group 3 - Question 1 - Child Question 3",
//               "description": null,
//               "critical": false,
//               "formula": null,
//               "question_type": "dropdown",
//               "question_sub_type": "text",
//               "question_hint": null,
//               "order": 3,
//               "is_required": true,
//               "require_live": false,
//               "number_of_file_allowed": null,
//               "min_value": null,
//               "max_value": null,
//               "max_score": null,
//               "is_logic_question": false,
//               "is_task_close_question": false,
//               "is_audit_info_question": false,
//               "is_other": true,
//               "form": 148,
//               "stage": null,
//               "audit_info": null,
//               "audit_group": 14,
//               "parent_question": 1361,
//               "sub_questions": [],
//               "logics": []
//             }
//           ],
//           "logics": []
//         }
//       ],
//       "created_at": "2025-08-07T11:16:54.146082Z",
//       "updated_at": null,
//       "name": "Audit Group 3",
//       "form": 148
//     }
//   ],
//   "created_at": "2025-08-07T11:16:53.247876Z",
//   "updated_at": null,
//   "form_type": "audit",
//   "title": "Audit Health & Safety Checklist5",
//   "prefix": "HSC",
//   "GPS": true,
//   "share_reponse": false,
//   "allow_editing": true,
//   "can_edit_previos_state": false,
//   "auto_share_reponse": false,
//   "pass_percentage": 80,
//   "max_score": 100,
//   "is_deleted": false,
//   "is_archived": false,
//   "last_deleted_date": null,
//   "last_archived_date": null,
//   "created_by": 85,
//   "updated_by": null,
//   "organization": 13,
//   "folder": 18,
//   "form_admin": 85,
//   "deletedBy": null,
//   "archivedBy": null
// }