export default [
  {
    id: 51,
    questions: [
      {
        id: 106,
        options: [],
        question_uuid: "question_uuid1",
        question: "Stage 1 - Question 1 - table",
        description: null,
        critical: false,
        formula: null,
        question_type: "table",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: 1,
        max_value: 4,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 45,
        stage: 51,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [
          {
            id: 107,
            options: [],
            question_uuid: "question_uuid2",
            question: "Stage 1 - Table Child Question 1 - location",
            description: null,
            critical: false,
            formula: null,
            question_type: "location",
            question_sub_type: null,
            question_hint: null,
            order: 1,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 45,
            stage: 51,
            audit_info: null,
            audit_group: null,
            parent_question: 106,
            sub_questions: [],
            logics: [],
          },
          {
            id: 108,
            options: [],
            question_uuid: "question_uuid3",
            question: "Stage 1 - Table Child Question 2 - division",
            description: null,
            critical: false,
            formula: null,
            question_type: "division",
            question_sub_type: null,
            question_hint: null,
            order: 2,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 45,
            stage: 51,
            audit_info: null,
            audit_group: null,
            parent_question: 106,
            sub_questions: [],
            logics: [],
          },
          {
            id: 121,
            options: [],
            question_uuid: "question_uuid16",
            question: "Stage 3 - Question 1 - title_and_description",
            description: "Question Description",
            critical: false,
            formula: null,
            question_type: "title_and_description",
            question_sub_type: null,
            question_hint: null,
            order: 1,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 45,
            stage: 53,
            audit_info: null,
            audit_group: null,
            parent_question: null,
            sub_questions: [],
            logics: [],
          },
          {
            id: 122,
            options: [],
            question_uuid: "question_uuid17",
            question: "Stage 3 - Question 2 - short_answer",
            description: null,
            critical: false,
            formula: null,
            question_type: "short_answer",
            question_sub_type: null,
            question_hint: "Question Hint",
            order: 2,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 45,
            stage: 53,
            audit_info: null,
            audit_group: null,
            parent_question: null,
            sub_questions: [],
            logics: [],
          },
          {
            id: 109,
            options: [
              {
                id: 57,
                created_at: "2025-07-17T18:29:13.051306Z",
                updated_at: null,
                option: "Stage 1 - Table Child Question 3 - Option 1",
                score: 0,
                failed: false,
                order: 1,
                question: 109,
                stage: 51,
                audit_info: null,
                audit_group: null,
                form: 45,
              },
              {
                id: 58,
                created_at: "2025-07-17T18:29:14.689569Z",
                updated_at: null,
                option: "Stage 1 - Table Child Question 3 - Option 2",
                score: 0,
                failed: false,
                order: 2,
                question: 109,
                stage: 51,
                audit_info: null,
                audit_group: null,
                form: 45,
              },
              {
                id: 59,
                created_at: "2025-07-17T18:29:16.277575Z",
                updated_at: null,
                option: "Stage 1 - Table Child Question 3 - Option 3",
                score: 0,
                failed: false,
                order: 3,
                question: 109,
                stage: 51,
                audit_info: null,
                audit_group: null,
                form: 45,
              },
            ],
            question_uuid: "question_uuid4",
            question: "Stage 1 - Table Child Question 3 - dropdown",
            description: null,
            critical: false,
            formula: null,
            question_type: "dropdown",
            question_sub_type: "text",
            question_hint: null,
            order: 3,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: true,
            form: 45,
            stage: 51,
            audit_info: null,
            audit_group: null,
            parent_question: 106,
            sub_questions: [],
            logics: [],
          },
          {
            id: 125,
            options: [
              {
                id: 63,
                created_at: "2025-07-17T18:29:52.679926Z",
                updated_at: null,
                option: "Stage 5 - Question 1 - Option 1",
                score: 0,
                failed: false,
                order: 1,
                question: 125,
                stage: 55,
                audit_info: null,
                audit_group: null,
                form: 45,
              },
              {
                id: 64,
                created_at: "2025-07-17T18:29:54.386963Z",
                updated_at: null,
                option: "Stage 5 - Question 1 - Option 2",
                score: 0,
                failed: false,
                order: 2,
                question: 125,
                stage: 55,
                audit_info: null,
                audit_group: null,
                form: 45,
              },
              {
                id: 65,
                created_at: "2025-07-17T18:29:56.179762Z",
                updated_at: null,
                option: "Stage 5 - Question 1 - Option 3",
                score: 0,
                failed: false,
                order: 3,
                question: 125,
                stage: 55,
                audit_info: null,
                audit_group: null,
                form: 45,
              },
            ],
            question_uuid: "question_uuid20",
            question: "Stage 5 - Question 1 - checkboxes",
            description: null,
            critical: false,
            formula: null,
            question_type: "checkboxes",
            question_sub_type: null,
            question_hint: null,
            order: 1,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 45,
            stage: 55,
            audit_info: null,
            audit_group: null,
            parent_question: null,
            sub_questions: [],
            logics: [],
          },
          {
            id: 137,
            options: [],
            question_uuid: "question_uuid32",
            question: "Stage 10 - Question 3 - user",
            description: null,
            critical: false,
            formula: null,
            question_type: "user",
            question_sub_type: null,
            question_hint: null,
            order: 3,
            is_required: true,
            require_live: false,
            number_of_file_allowed: null,
            min_value: null,
            max_value: null,
            max_score: null,
            is_logic_question: false,
            is_task_close_question: false,
            is_audit_info_question: false,
            is_other: false,
            form: 45,
            stage: 60,
            audit_info: null,
            audit_group: null,
            parent_question: null,
            sub_questions: [],
            logics: [],
          },
        ],
        logics: [
          {
            id: 4,
            logic_questions: [
              {
                id: 110,
                options: [],
                created_at: "2025-07-17T18:29:17.760214Z",
                updated_at: null,
                question_uuid: "question_uuid7",
                question: "Logic 1 question 1",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 45,
                stage: 51,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
              {
                id: 111,
                options: [],
                created_at: "2025-07-17T18:29:18.786566Z",
                updated_at: null,
                question_uuid: "question_uuid8",
                question: "Logic 1 question 2",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 2,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 45,
                stage: 51,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-17T18:29:17.263628Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "YES",
            notification: false,
            email: null,
            order: 1,
            user: null,
            group: null,
            form: 45,
            stage: 51,
            audit_info: null,
            audit_group: null,
            question: 106,
            follow_up: {
              task_close_questions: [
                {
                  id: 112,
                  options: [],
                  created_at: "2025-07-17T18:29:20.114965Z",
                  updated_at: null,
                  question_uuid: "question_uuid5",
                  question: "LOGIC 1 - FOLLOW UP TASK CLOSE QUESTION 1",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "date",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 45,
                  stage: 51,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
                {
                  id: 113,
                  options: [],
                  created_at: "2025-07-17T18:29:20.577516Z",
                  updated_at: null,
                  question_uuid: "question_uuid6",
                  question: "LOGIC 1 - FOLLOW UP TASK CLOSE QUESTION 2",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "time",
                  question_sub_type: null,
                  question_hint: null,
                  order: 2,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 45,
                  stage: 51,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
              ],
              title: "LOGIC 1 - Followup title 1",
              deadline: 30,
              assign_to: "form_submitter",
              logic: 4,
              assign_form: null,
              user: null,
              group: null,
              form: 45,
              stage: 51,
              audit_info: null,
              audit_group: null,
              question: 106,
            },
          },
          {
            id: 5,
            logic_questions: [
              {
                id: 114,
                options: [],
                created_at: "2025-07-17T18:29:22.556076Z",
                updated_at: null,
                question_uuid: "question_uuid11",
                question: "Logic 2 question 1",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 1,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 45,
                stage: 51,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
              {
                id: 115,
                options: [],
                created_at: "2025-07-17T18:29:23.701616Z",
                updated_at: null,
                question_uuid: "question_uuid12",
                question: "Logic 2 question 2",
                description: null,
                critical: false,
                formula: null,
                question_type: "division",
                question_sub_type: null,
                question_hint: null,
                order: 2,
                is_required: true,
                require_live: false,
                number_of_file_allowed: null,
                min_value: 1,
                max_value: 2,
                max_score: null,
                is_logic_question: true,
                is_task_close_question: false,
                is_audit_info_question: false,
                is_other: false,
                form: 45,
                stage: 51,
                audit_info: null,
                audit_group: null,
                parent_question: null,
              },
            ],
            created_at: "2025-07-17T18:29:22.099605Z",
            updated_at: null,
            logic_type: "is",
            logic_value: "NO",
            notification: false,
            email: null,
            order: 2,
            user: null,
            group: null,
            form: 45,
            stage: 51,
            audit_info: null,
            audit_group: null,
            question: 106,
            follow_up: {
              task_close_questions: [
                {
                  id: 116,
                  options: [],
                  created_at: "2025-07-17T18:29:25.145399Z",
                  updated_at: null,
                  question_uuid: "question_uuid9",
                  question: "LOGIC 2 - FOLLOW UP TASK CLOSE QUESTION 1",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "date",
                  question_sub_type: null,
                  question_hint: null,
                  order: 1,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 45,
                  stage: 51,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
                {
                  id: 117,
                  options: [],
                  created_at: "2025-07-17T18:29:25.603296Z",
                  updated_at: null,
                  question_uuid: "question_uuid10",
                  question: "LOGIC 2 - FOLLOW UP TASK CLOSE QUESTION 1",
                  description: null,
                  critical: false,
                  formula: null,
                  question_type: "time",
                  question_sub_type: null,
                  question_hint: null,
                  order: 2,
                  is_required: true,
                  require_live: false,
                  number_of_file_allowed: null,
                  min_value: null,
                  max_value: null,
                  max_score: null,
                  is_logic_question: false,
                  is_task_close_question: true,
                  is_audit_info_question: false,
                  is_other: false,
                  form: 45,
                  stage: 51,
                  audit_info: null,
                  audit_group: null,
                  parent_question: null,
                },
              ],
              title: "LOGIC 2 - Followup title 2",
              deadline: 30,
              assign_to: "form_submitter",
              logic: 5,
              assign_form: null,
              user: null,
              group: null,
              form: 45,
              stage: 51,
              audit_info: null,
              audit_group: null,
              question: 106,
            },
          },
        ],
      },
      // {
      //   id: 118,
      //   options: [],
      //   question_uuid: "question_uuid13",
      //   question: "Stage 2- Question 2 - location",
      //   description: null,
      //   critical: false,
      //   formula: null,
      //   question_type: "location",
      //   question_sub_type: null,
      //   question_hint: null,
      //   order: 2,
      //   is_required: true,
      //   require_live: false,
      //   number_of_file_allowed: null,
      //   min_value: null,
      //   max_value: null,
      //   max_score: null,
      //   is_logic_question: false,
      //   is_task_close_question: false,
      //   is_audit_info_question: false,
      //   is_other: false,
      //   form: 45,
      //   stage: 51,
      //   audit_info: null,
      //   audit_group: null,
      //   parent_question: null,
      //   sub_questions: [],
      //   logics: [],
      // },
      {
        id: 124,
        options: [
          {
            id: 60,
            created_at: "2025-07-17T18:29:42.149422Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 124,
            stage: 54,
            audit_info: null,
            audit_group: null,
            form: 45,
          },
          {
            id: 61,
            created_at: "2025-07-17T18:29:43.974645Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 124,
            stage: 54,
            audit_info: null,
            audit_group: null,
            form: 45,
          },
          {
            id: 62,
            created_at: "2025-07-17T18:29:45.918596Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 124,
            stage: 54,
            audit_info: null,
            audit_group: null,
            form: 45,
          },
        ],
        question_uuid: "question_uuid19",
        question: "Stage 4 - Question 2 - multiple_choice",
        description: null,
        critical: false,
        formula: null,
        question_type: "multiple_choice",
        question_sub_type: "text",
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: true,
        form: 45,
        stage: 54,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-17T18:29:05.674991Z",
    updated_at: null,
    name: "Stage 1",
    order: 1,
    form: 45,
  },
  // {
  //   id: 52,
  //   questions: [
  //     {
  //       id: 119,
  //       options: [],
  //       question_uuid: "question_uuid14",
  //       question: "Stage 2 - Question 1 - division",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "division",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 52,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 120,
  //       options: [],
  //       question_uuid: "question_uuid15",
  //       question: "Stage 2 - Question 2 - sub_division",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "sub_division",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 52,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:29:29.351605Z",
  //   updated_at: null,
  //   name: "Stage 2",
  //   order: 2,
  //   form: 45,
  // },
  // {
  //   id: 53,
  //   questions: [
  //     {
  //       id: 121,
  //       options: [],
  //       question_uuid: "question_uuid16",
  //       question: "Stage 3 - Question 1 - title_and_description",
  //       description: "Question Description",
  //       critical: false,
  //       formula: null,
  //       question_type: "title_and_description",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 53,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 122,
  //       options: [],
  //       question_uuid: "question_uuid17",
  //       question: "Stage 3 - Question 2 - short_answer",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "short_answer",
  //       question_sub_type: null,
  //       question_hint: "Question Hint",
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 53,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:29:33.102153Z",
  //   updated_at: null,
  //   name: "Stage 3",
  //   order: 3,
  //   form: 45,
  // },
  // {
  //   id: 54,
  //   questions: [
  //     {
  //       id: 123,
  //       options: [],
  //       question_uuid: "question_uuid18",
  //       question: "Stage 4 - Question 1 - long_answer",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "long_answer",
  //       question_sub_type: null,
  //       question_hint: "Question Hint",
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 54,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 124,
  //       options: [
  //         {
  //           id: 60,
  //           created_at: "2025-07-17T18:29:42.149422Z",
  //           updated_at: null,
  //           option: "Stage 4 - Question 2 - Option 1",
  //           score: 0,
  //           failed: false,
  //           order: 1,
  //           question: 124,
  //           stage: 54,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 61,
  //           created_at: "2025-07-17T18:29:43.974645Z",
  //           updated_at: null,
  //           option: "Stage 4 - Question 2 - Option 2",
  //           score: 0,
  //           failed: false,
  //           order: 2,
  //           question: 124,
  //           stage: 54,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 62,
  //           created_at: "2025-07-17T18:29:45.918596Z",
  //           updated_at: null,
  //           option: "Stage 4 - Question 2 - Option 3",
  //           score: 0,
  //           failed: false,
  //           order: 3,
  //           question: 124,
  //           stage: 54,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //       ],
  //       question_uuid: "question_uuid19",
  //       question: "Stage 4 - Question 2 - multiple_choice",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "multiple_choice",
  //       question_sub_type: "text",
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: true,
  //       form: 45,
  //       stage: 54,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:29:37.585601Z",
  //   updated_at: null,
  //   name: "Stage 4",
  //   order: 4,
  //   form: 45,
  // },
  // {
  //   id: 55,
  //   questions: [
  //     {
  //       id: 125,
  //       options: [
  //         {
  //           id: 63,
  //           created_at: "2025-07-17T18:29:52.679926Z",
  //           updated_at: null,
  //           option: "Stage 5 - Question 1 - Option 1",
  //           score: 0,
  //           failed: false,
  //           order: 1,
  //           question: 125,
  //           stage: 55,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 64,
  //           created_at: "2025-07-17T18:29:54.386963Z",
  //           updated_at: null,
  //           option: "Stage 5 - Question 1 - Option 2",
  //           score: 0,
  //           failed: false,
  //           order: 2,
  //           question: 125,
  //           stage: 55,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 65,
  //           created_at: "2025-07-17T18:29:56.179762Z",
  //           updated_at: null,
  //           option: "Stage 5 - Question 1 - Option 3",
  //           score: 0,
  //           failed: false,
  //           order: 3,
  //           question: 125,
  //           stage: 55,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //       ],
  //       question_uuid: "question_uuid20",
  //       question: "Stage 5 - Question 1 - checkboxes",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "checkboxes",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 55,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 126,
  //       options: [
  //         {
  //           id: 66,
  //           created_at: "2025-07-17T18:29:59.559907Z",
  //           updated_at: null,
  //           option: "Stage 5 - Question 2 - Option 1",
  //           score: 0,
  //           failed: false,
  //           order: 1,
  //           question: 126,
  //           stage: 55,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 67,
  //           created_at: "2025-07-17T18:30:01.289929Z",
  //           updated_at: null,
  //           option: "Stage 5 - Question 2 - Option 2",
  //           score: 0,
  //           failed: false,
  //           order: 2,
  //           question: 126,
  //           stage: 55,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 68,
  //           created_at: "2025-07-17T18:30:03.021486Z",
  //           updated_at: null,
  //           option: "Stage 5 - Question 2 - Option 3",
  //           score: 0,
  //           failed: false,
  //           order: 3,
  //           question: 126,
  //           stage: 55,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //       ],
  //       question_uuid: "question_uuid21",
  //       question: "Stage 5 - Question 2 - dropdown",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "dropdown",
  //       question_sub_type: "text",
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: true,
  //       form: 45,
  //       stage: 55,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:29:49.192448Z",
  //   updated_at: null,
  //   name: "Stage 5",
  //   order: 5,
  //   form: 45,
  // },
  // {
  //   id: 56,
  //   questions: [
  //     {
  //       id: 127,
  //       options: [
  //         {
  //           id: 69,
  //           created_at: "2025-07-17T18:30:08.469484Z",
  //           updated_at: null,
  //           option: "Stage 6 - Question 1 - Option 1",
  //           score: 0,
  //           failed: false,
  //           order: 1,
  //           question: 127,
  //           stage: 56,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //         {
  //           id: 70,
  //           created_at: "2025-07-17T18:30:10.428717Z",
  //           updated_at: null,
  //           option: "Stage 6 - Question 1 - Option 2",
  //           score: 0,
  //           failed: false,
  //           order: 2,
  //           question: 127,
  //           stage: 56,
  //           audit_info: null,
  //           audit_group: null,
  //           form: 45,
  //         },
  //       ],
  //       question_uuid: "question_uuid22",
  //       question: "Stage 6 - Question 1 - linear_scale",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "linear_scale",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: 1,
  //       max_value: 10,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 56,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 128,
  //       options: [],
  //       question_uuid: "question_uuid23",
  //       question: "Stage 6 - Question 2 - datetime",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "datetime",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 56,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:30:05.274046Z",
  //   updated_at: null,
  //   name: "Stage 6",
  //   order: 6,
  //   form: 45,
  // },
  // {
  //   id: 57,
  //   questions: [
  //     {
  //       id: 129,
  //       options: [],
  //       question_uuid: "question_uuid24",
  //       question: "Stage 7 - Question 1 - date",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "date",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 57,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 130,
  //       options: [],
  //       question_uuid: "question_uuid25",
  //       question: "Stage 7 - Question 2 - time",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "time",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 57,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:30:13.260982Z",
  //   updated_at: null,
  //   name: "Stage 7",
  //   order: 7,
  //   form: 45,
  // },
  // {
  //   id: 58,
  //   questions: [
  //     {
  //       id: 131,
  //       options: [],
  //       question_uuid: "question_uuid26",
  //       question: "Stage 8 - Question 1 - signature",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "signature",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 58,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 132,
  //       options: [],
  //       question_uuid: "question_uuid27",
  //       question: "Stage 8 - Question 2 - upload_image",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "upload_image",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: true,
  //       number_of_file_allowed: 5,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 58,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:30:17.032539Z",
  //   updated_at: null,
  //   name: "Stage 8",
  //   order: 8,
  //   form: 45,
  // },
  // {
  //   id: 59,
  //   questions: [
  //     {
  //       id: 133,
  //       options: [],
  //       question_uuid: "question_uuid28",
  //       question: "Stage 9 - Question 1 - upload_video",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "upload_video",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 1,
  //       is_required: true,
  //       require_live: true,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 59,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     {
  //       id: 134,
  //       options: [],
  //       question_uuid: "question_uuid29",
  //       question: "Stage 9 - Question 2 - upload_file",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "upload_file",
  //       question_sub_type: null,
  //       question_hint: null,
  //       order: 2,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: 3,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 59,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //   ],
  //   created_at: "2025-07-17T18:30:21.146608Z",
  //   updated_at: null,
  //   name: "Stage 9",
  //   order: 9,
  //   form: 45,
  // },
  // {
  //   id: 60,
  //   questions: [
  //     {
  //       id: 135,
  //       options: [],
  //       question_uuid: "question_uuid30",
  //       question: "Stage 10 - Question 1 - qr_code",
  //       description: null,
  //       critical: false,
  //       formula: null,
  //       question_type: "qr_code",
  //       question_sub_type: null,
  //       question_hint: "Stage 10 - Question 1 - qr_code - Question Hint",
  //       order: 1,
  //       is_required: true,
  //       require_live: false,
  //       number_of_file_allowed: null,
  //       min_value: null,
  //       max_value: null,
  //       max_score: null,
  //       is_logic_question: false,
  //       is_task_close_question: false,
  //       is_audit_info_question: false,
  //       is_other: false,
  //       form: 45,
  //       stage: 60,
  //       audit_info: null,
  //       audit_group: null,
  //       parent_question: null,
  //       sub_questions: [],
  //       logics: [],
  //     },
  //     // {
  //     //   id: 136,
  //     //   options: [],
  //     //   question_uuid: "question_uuid31",
  //     //   question: "Stage 10 - Question 2 - formula",
  //     //   description: null,
  //     //   critical: false,
  //     //   formula: "SUM(asdasd+asdasd)*asdsd",
  //     //   question_type: "formula",
  //     //   question_sub_type: null,
  //     //   question_hint: null,
  //     //   order: 2,
  //     //   is_required: true,
  //     //   require_live: false,
  //     //   number_of_file_allowed: null,
  //     //   min_value: null,
  //     //   max_value: null,
  //     //   max_score: null,
  //     //   is_logic_question: false,
  //     //   is_task_close_question: false,
  //     //   is_audit_info_question: false,
  //     //   is_other: false,
  //     //   form: 45,
  //     //   stage: 60,
  //     //   audit_info: null,
  //     //   audit_group: null,
  //     //   parent_question: null,
  //     //   sub_questions: [],
  //     //   logics: [],
  //     // },
  //     // {
  //     //   id: 137,
  //     //   options: [],
  //     //   question_uuid: "question_uuid32",
  //     //   question: "Stage 10 - Question 3 - user",
  //     //   description: null,
  //     //   critical: false,
  //     //   formula: null,
  //     //   question_type: "user",
  //     //   question_sub_type: null,
  //     //   question_hint: null,
  //     //   order: 3,
  //     //   is_required: true,
  //     //   require_live: false,
  //     //   number_of_file_allowed: null,
  //     //   min_value: null,
  //     //   max_value: null,
  //     //   max_score: null,
  //     //   is_logic_question: false,
  //     //   is_task_close_question: false,
  //     //   is_audit_info_question: false,
  //     //   is_other: false,
  //     //   form: 45,
  //     //   stage: 60,
  //     //   audit_info: null,
  //     //   audit_group: null,
  //     //   parent_question: null,
  //     //   sub_questions: [],
  //     //   logics: [],
  //     // },
  //   ],
  //   created_at: "2025-07-17T18:30:25.345619Z",
  //   updated_at: null,
  //   name: "Stage 10",
  //   order: 10,
  //   form: 45,
  // },
];
