import { Stage } from "@/types/forms";

// export const stagesData: Stage[] = [
// //   {
// //     id: 82,
// //     questions: [
// //       {
// //         id: 226,
// //         options: [],
// //         question_uuid: "question_uuid16",
// //         question: "Stage 3 - Question 1 - title_and_description",
// //         description: "Question Description",
// //         critical: false,
// //         formula: null,
// //         question_type: "title_and_description",
// //         question_sub_type: null,
// //         question_hint: null,
// //         order: 1,
// //         is_required: true,
// //         require_live: false,
// //         number_of_file_allowed: null,
// //         min_value: null,
// //         max_value: null,
// //         max_score: null,
// //         is_logic_question: false,
// //         is_task_close_question: false,
// //         is_audit_info_question: false,
// //         is_other: false,
// //         form: 69,
// //         stage: 84,
// //         audit_info: null,
// //         audit_group: null,
// //         parent_question: null,
// //         sub_questions: [],
// //         logics: [],
// //       },
// //       {
// //         id: 227,
// //         options: [],
// //         question_uuid: "question_uuid17",
// //         question: "Stage 3 - Question 2 - short_answer",
// //         description: null,
// //         critical: false,
// //         formula: null,
// //         question_type: "short_answer",
// //         question_sub_type: null,
// //         question_hint: "Question Hint",
// //         order: 2,
// //         is_required: true,
// //         require_live: false,
// //         number_of_file_allowed: null,
// //         min_value: null,
// //         max_value: null,
// //         max_score: null,
// //         is_logic_question: false,
// //         is_task_close_question: false,
// //         is_audit_info_question: false,
// //         is_other: false,
// //         form: 69,
// //         stage: 84,
// //         audit_info: null,
// //         audit_group: null,
// //         parent_question: null,
// //         sub_questions: [],
// //         logics: [],
// //       },
// //     ],
// //     created_at: "2025-07-14T09:05:12.420924Z",
// //     updated_at: null,
// //     name: "Stage 1 is to filled by the users",
// //     order: 3,
// //     form: 69,
// //   },
//   {
//     id: 84,
//     questions: [
//       {
//         id: 237,
//         options: [],
//         question_uuid: "question_uuid17",
//         question: "Stage 3 - Question 2 - short_answer",
//         description: null,
//         critical: false,
//         formula: null,
//         question_type: "short_answer",
//         question_sub_type: null,
//         question_hint: "Question Hint",
//         order: 2,
//         is_required: true,
//         require_live: false,
//         number_of_file_allowed: null,
//         min_value: null,
//         max_value: null,
//         max_score: null,
//         is_logic_question: false,
//         is_task_close_question: false,
//         is_audit_info_question: false,
//         is_other: false,
//         form: 69,
//         stage: 84,
//         audit_info: null,
//         audit_group: null,
//         parent_question: null,
//         sub_questions: [],
//         logics: [],
//       },
//       {
//         id: 236,
//         options: [],
//         question_uuid: "question_uuid16",
//         question: "Stage 3 - Question 1 - title_and_description",
//         description: "Question Description",
//         critical: false,
//         formula: null,
//         question_type: "title_and_description",
//         question_sub_type: null,
//         question_hint: null,
//         order: 1,
//         is_required: true,
//         require_live: false,
//         number_of_file_allowed: null,
//         min_value: null,
//         max_value: null,
//         max_score: null,
//         is_logic_question: false,
//         is_task_close_question: false,
//         is_audit_info_question: false,
//         is_other: false,
//         form: 69,
//         stage: 84,
//         audit_info: null,
//         audit_group: null,
//         parent_question: null,
//         sub_questions: [],
//         logics: [],
//       },
//     ],
//     created_at: "2025-07-14T09:05:12.420924Z",
//     updated_at: null,
//     name: "Stage 2",
//     order: 3,
//     form: 69,
//   },

//           {
//             "id": 86,
//             "questions": [
//                 {
//                     "id": 240,
//                     "options": [
//                         {
//                             "id": 60,
//                             "created_at": "2025-07-14T09:05:12.549959Z",
//                             "updated_at": null,
//                             "option": "Stage 5 - Question 1 - Option 1",
//                             "score": 0,
//                             "failed": false,
//                             "order": 1,
//                             "question": 240,
//                             "stage": 86,
//                             "audit_info": null,
//                             "audit_group": null,
//                             "form": 69
//                         },
//                         {
//                             "id": 61,
//                             "created_at": "2025-07-14T09:05:12.558683Z",
//                             "updated_at": null,
//                             "option": "Stage 5 - Question 1 - Option 2",
//                             "score": 0,
//                             "failed": false,
//                             "order": 2,
//                             "question": 240,
//                             "stage": 86,
//                             "audit_info": null,
//                             "audit_group": null,
//                             "form": 69
//                         },
//                         {
//                             "id": 62,
//                             "created_at": "2025-07-14T09:05:12.569571Z",
//                             "updated_at": null,
//                             "option": "Stage 5 - Question 1 - Option 3",
//                             "score": 0,
//                             "failed": false,
//                             "order": 3,
//                             "question": 240,
//                             "stage": 86,
//                             "audit_info": null,
//                             "audit_group": null,
//                             "form": 69
//                         }
//                     ],
//                     "question_uuid": "question_uuid20",
//                     "question": "Stage 5 - Question 1 - checkboxes",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "checkboxes",
//                     "question_sub_type": null,
//                     "question_hint": null,
//                     "order": 1,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": false,
//                     "is_audit_info_question": false,
//                     "is_other": false,
//                     "form": 69,
//                     "stage": 86,
//                     "audit_info": null,
//                     "audit_group": null,
//                     "parent_question": null,
//                     "sub_questions": [],
//                     "logics": []
//                 },
//                 {
//                     "id": 241,
//                     "options": [
//                         {
//                             "id": 63,
//                             "created_at": "2025-07-14T09:05:12.591135Z",
//                             "updated_at": null,
//                             "option": "Stage 5 - Question 2 - Option 1",
//                             "score": 0,
//                             "failed": false,
//                             "order": 1,
//                             "question": 241,
//                             "stage": 86,
//                             "audit_info": null,
//                             "audit_group": null,
//                             "form": 69
//                         },
//                         {
//                             "id": 64,
//                             "created_at": "2025-07-14T09:05:12.601936Z",
//                             "updated_at": null,
//                             "option": "Stage 5 - Question 2 - Option 2",
//                             "score": 0,
//                             "failed": false,
//                             "order": 2,
//                             "question": 241,
//                             "stage": 86,
//                             "audit_info": null,
//                             "audit_group": null,
//                             "form": 69
//                         },
//                         {
//                             "id": 65,
//                             "created_at": "2025-07-14T09:05:12.611531Z",
//                             "updated_at": null,
//                             "option": "Stage 5 - Question 2 - Option 3",
//                             "score": 0,
//                             "failed": false,
//                             "order": 3,
//                             "question": 241,
//                             "stage": 86,
//                             "audit_info": null,
//                             "audit_group": null,
//                             "form": 69
//                         }
//                     ],
//                     "question_uuid": "question_uuid21",
//                     "question": "Stage 5 - Question 2 - dropdown",
//                     "description": null,
//                     "critical": false,
//                     "formula": null,
//                     "question_type": "dropdown",
//                     "question_sub_type": "text",
//                     "question_hint": null,
//                     "order": 2,
//                     "is_required": true,
//                     "require_live": false,
//                     "number_of_file_allowed": null,
//                     "min_value": null,
//                     "max_value": null,
//                     "max_score": null,
//                     "is_logic_question": false,
//                     "is_task_close_question": false,
//                     "is_audit_info_question": false,
//                     "is_other": true,
//                     "form": 69,
//                     "stage": 86,
//                     "audit_info": null,
//                     "audit_group": null,
//                     "parent_question": null,
//                     "sub_questions": [],
//                     "logics": []
//                 }
//             ],
//             "created_at": "2025-07-14T09:05:12.525992Z",
//             "updated_at": null,
//             "name": "Stage 3",
//             "order": 5,
//             "form": 69
//         },
// ];

export const stagesData: Stage[] = [
  //   {
  //     id: 82,
  //     questions: [
  //       {
  //         id: 221,
  //         options: [],
  //         question_uuid: "question_uuid1",
  //         question: "Stage 1 - Question 1 - table",
  //         description: null,
  //         critical: false,
  //         formula: null,
  //         question_type: "table",
  //         question_sub_type: null,
  //         question_hint: null,
  //         order: 1,
  //         is_required: true,
  //         require_live: false,
  //         number_of_file_allowed: null,
  //         min_value: 1,
  //         max_value: 2,
  //         max_score: null,
  //         is_logic_question: false,
  //         is_task_close_question: false,
  //         is_audit_info_question: false,
  //         is_other: false,
  //         form: 69,
  //         stage: 82,
  //         audit_info: null,
  //         audit_group: null,
  //         parent_question: null,
  //         sub_questions: [
  //           {
  //             id: 222,
  //             options: [],
  //             question_uuid: "question_uuid2",
  //             question: "Stage 1 - Table Child Question 1 - location",
  //             description: null,
  //             critical: false,
  //             formula: null,
  //             question_type: "location",
  //             question_sub_type: null,
  //             question_hint: null,
  //             order: 1,
  //             is_required: true,
  //             require_live: false,
  //             number_of_file_allowed: null,
  //             min_value: null,
  //             max_value: null,
  //             max_score: null,
  //             is_logic_question: false,
  //             is_task_close_question: false,
  //             is_audit_info_question: false,
  //             is_other: false,
  //             form: 69,
  //             stage: 82,
  //             audit_info: null,
  //             audit_group: null,
  //             parent_question: 221,
  //             sub_questions: [],
  //             logics: [],
  //           },
  //           {
  //             id: 223,
  //             options: [],
  //             question_uuid: "question_uuid3",
  //             question: "Stage 1 - Table Child Question 2 - division",
  //             description: null,
  //             critical: false,
  //             formula: null,
  //             question_type: "division",
  //             question_sub_type: null,
  //             question_hint: null,
  //             order: 2,
  //             is_required: true,
  //             require_live: false,
  //             number_of_file_allowed: null,
  //             min_value: null,
  //             max_value: null,
  //             max_score: null,
  //             is_logic_question: false,
  //             is_task_close_question: false,
  //             is_audit_info_question: false,
  //             is_other: false,
  //             form: 69,
  //             stage: 82,
  //             audit_info: null,
  //             audit_group: null,
  //             parent_question: 221,
  //             sub_questions: [],
  //             logics: [],
  //           },
  //           {
  //             id: 224,
  //             options: [
  //               {
  //                 id: 54,
  //                 created_at: "2025-07-14T09:05:12.245585Z",
  //                 updated_at: null,
  //                 option: "Stage 1 - Table Child Question 3 - Option 1",
  //                 score: 0,
  //                 failed: false,
  //                 order: 1,
  //                 question: 224,
  //                 stage: 82,
  //                 audit_info: null,
  //                 audit_group: null,
  //                 form: 69,
  //               },
  //               {
  //                 id: 55,
  //                 created_at: "2025-07-14T09:05:12.257518Z",
  //                 updated_at: null,
  //                 option: "Stage 1 - Table Child Question 3 - Option 2",
  //                 score: 0,
  //                 failed: false,
  //                 order: 2,
  //                 question: 224,
  //                 stage: 82,
  //                 audit_info: null,
  //                 audit_group: null,
  //                 form: 69,
  //               },
  //               {
  //                 id: 56,
  //                 created_at: "2025-07-14T09:05:12.267488Z",
  //                 updated_at: null,
  //                 option: "Stage 1 - Table Child Question 3 - Option 3",
  //                 score: 0,
  //                 failed: false,
  //                 order: 3,
  //                 question: 224,
  //                 stage: 82,
  //                 audit_info: null,
  //                 audit_group: null,
  //                 form: 69,
  //               },
  //             ],
  //             question_uuid: "question_uuid4",
  //             question: "Stage 1 - Table Child Question 3 - dropdown",
  //             description: null,
  //             critical: false,
  //             formula: null,
  //             question_type: "dropdown",
  //             question_sub_type: "text",
  //             question_hint: null,
  //             order: 3,
  //             is_required: true,
  //             require_live: false,
  //             number_of_file_allowed: null,
  //             min_value: null,
  //             max_value: null,
  //             max_score: null,
  //             is_logic_question: false,
  //             is_task_close_question: false,
  //             is_audit_info_question: false,
  //             is_other: true,
  //             form: 69,
  //             stage: 82,
  //             audit_info: null,
  //             audit_group: null,
  //             parent_question: 221,
  //             sub_questions: [],
  //             logics: [],
  //           },
  //         ],
  //         logics: [
  //           {
  //             id: 3,
  //             logic_questions: [
  //               {
  //                   id: 225,
  //                   options: [],
  //                   question_uuid: "question_uuid7",
  //                   question: "Logic 1 question 1",
  //                   description: null,
  //                   critical: false,
  //                   formula: null,
  //                   question_type: "division",
  //                   question_sub_type: null,
  //                   question_hint: null,
  //                   order: 1,
  //                   is_required: true,
  //                   require_live: false,
  //                   number_of_file_allowed: null,
  //                   min_value: 1,
  //                   max_value: 2,
  //                   max_score: null,
  //                   is_logic_question: true,
  //                   is_task_close_question: false,
  //                   is_audit_info_question: false,
  //                   is_other: false,
  //                   form: 69,
  //                   stage: 82,
  //                   audit_info: null,
  //                   audit_group: null,
  //                   parent_question: null,
  //                   sub_questions: [],
  //                   logics: []
  //               },
  //               {
  //                   id: 226,
  //                   options: [],
  //                   question_uuid: "question_uuid8",
  //                   question: "Logic 1 question 2",
  //                   description: null,
  //                   critical: false,
  //                   formula: null,
  //                   question_type: "division",
  //                   question_sub_type: null,
  //                   question_hint: null,
  //                   order: 2,
  //                   is_required: true,
  //                   require_live: false,
  //                   number_of_file_allowed: null,
  //                   min_value: 1,
  //                   max_value: 2,
  //                   max_score: null,
  //                   is_logic_question: true,
  //                   is_task_close_question: false,
  //                   is_audit_info_question: false,
  //                   is_other: false,
  //                   form: 69,
  //                   stage: 82,
  //                   audit_info: null,
  //                   audit_group: null,
  //                   parent_question: null,
  //                   sub_questions: [],
  //                   logics: []
  //               },
  //             ],
  //             created_at: "2025-07-14T09:05:12.278379Z",
  //             updated_at: null,
  //             logic_type: "is",
  //             logic_value: "YES",
  //             notification: false,
  //             email: null,
  //             order: 1,
  //             user: null,
  //             group: null,
  //             form: 69,
  //             stage: 82,
  //             audit_info: null,
  //             audit_group: null,
  //             question: 221,
  //             follow_up: {
  //               task_close_questions: [
  //                 {
  //                     id: 227,
  //                     options: [],
  //                     question_uuid: "question_uuid5",
  //                     question: "LOGIC 1 - FOLLOW UP TASK CLOSE QUESTION 1",
  //                     description: null,
  //                     critical: false,
  //                     formula: null,
  //                     question_type: "date",
  //                     question_sub_type: null,
  //                     question_hint: null,
  //                     order: 1,
  //                     is_required: true,
  //                     require_live: false,
  //                     number_of_file_allowed: null,
  //                     min_value: null,
  //                     max_value: null,
  //                     max_score: null,
  //                     is_logic_question: false,
  //                     is_task_close_question: true,
  //                     is_audit_info_question: false,
  //                     is_other: false,
  //                     form: 69,
  //                     stage: 82,
  //                     audit_info: null,
  //                     audit_group: null,
  //                     parent_question: null,
  //                     sub_questions: [],
  //                     logics: []
  //                 },
  //                 {
  //                     id: 228,
  //                     options: [],
  //                     question_uuid: "question_uuid6",
  //                     question: "LOGIC 1 - FOLLOW UP TASK CLOSE QUESTION 2",
  //                     description: null,
  //                     critical: false,
  //                     formula: null,
  //                     question_type: "time",
  //                     question_sub_type: null,
  //                     question_hint: null,
  //                     order: 2,
  //                     is_required: true,
  //                     require_live: false,
  //                     number_of_file_allowed: null,
  //                     min_value: null,
  //                     max_value: null,
  //                     max_score: null,
  //                     is_logic_question: false,
  //                     is_task_close_question: true,
  //                     is_audit_info_question: false,
  //                     is_other: false,
  //                     form: 69,
  //                     stage: 82,
  //                     audit_info: null,
  //                     audit_group: null,
  //                     parent_question: null,
  //                     sub_questions: [],
  //                     logics: []
  //                 },
  //               ],
  //               title: "LOGIC 1 - Followup title 1",
  //               deadline: 30,
  //               assign_to: "form_submitter",
  //               logic: 3,
  //               assign_form: null,
  //               user: null,
  //               group: null,
  //               form: 69,
  //               stage: 82,
  //               audit_info: null,
  //               audit_group: null,
  //               question: 221,
  //             },
  //           },
  //           {
  //             id: 4,
  //             logic_questions: [
  //               {
  //                   id: 229,
  //                   options: [],
  //                   question_uuid: "question_uuid11",
  //                   question: "Logic 2 question 1",
  //                   description: null,
  //                   critical: false,
  //                   formula: null,
  //                   question_type: "division",
  //                   question_sub_type: null,
  //                   question_hint: null,
  //                   order: 1,
  //                   is_required: true,
  //                   require_live: false,
  //                   number_of_file_allowed: null,
  //                   min_value: 1,
  //                   max_value: 2,
  //                   max_score: null,
  //                   is_logic_question: true,
  //                   is_task_close_question: false,
  //                   is_audit_info_question: false,
  //                   is_other: false,
  //                   form: 69,
  //                   stage: 82,
  //                   audit_info: null,
  //                   audit_group: null,
  //                   parent_question: null,
  //                   sub_questions: [],
  //                   logics: []
  //               },
  //               {
  //                   id: 230,
  //                   options: [],
  //                   question_uuid: "question_uuid12",
  //                   question: "Logic 2 question 2",
  //                   description: null,
  //                   critical: false,
  //                   formula: null,
  //                   question_type: "division",
  //                   question_sub_type: null,
  //                   question_hint: null,
  //                   order: 2,
  //                   is_required: true,
  //                   require_live: false,
  //                   number_of_file_allowed: null,
  //                   min_value: 1,
  //                   max_value: 2,
  //                   max_score: null,
  //                   is_logic_question: true,
  //                   is_task_close_question: false,
  //                   is_audit_info_question: false,
  //                   is_other: false,
  //                   form: 69,
  //                   stage: 82,
  //                   audit_info: null,
  //                   audit_group: null,
  //                   parent_question: null,
  //                   sub_questions: [],
  //                   logics: []
  //               },
  //             ],
  //             created_at: "2025-07-14T09:05:12.353303Z",
  //             updated_at: null,
  //             logic_type: "is",
  //             logic_value: "NO",
  //             notification: false,
  //             email: null,
  //             order: 2,
  //             user: null,
  //             group: null,
  //             form: 69,
  //             stage: 82,
  //             audit_info: null,
  //             audit_group: null,
  //             question: 221,
  //             follow_up: {
  //               task_close_questions: [
  //                 {
  //                     id: 231,
  //                     options: [],
  //                     question_uuid: "question_uuid9",
  //                     question: "LOGIC 2 - FOLLOW UP TASK CLOSE QUESTION 1",
  //                     description: null,
  //                     critical: false,
  //                     formula: null,
  //                     question_type: "date",
  //                     question_sub_type: null,
  //                     question_hint: null,
  //                     order: 1,
  //                     is_required: true,
  //                     require_live: false,
  //                     number_of_file_allowed: null,
  //                     min_value: null,
  //                     max_value: null,
  //                     max_score: null,
  //                     is_logic_question: false,
  //                     is_task_close_question: true,
  //                     is_audit_info_question: false,
  //                     is_other: false,
  //                     form: 69,
  //                     stage: 82,
  //                     audit_info: null,
  //                     audit_group: null,
  //                     parent_question: null,
  //                     sub_questions: [],
  //                     logics: []
  //                 },
  //                 {
  //                     id: 232,
  //                     options: [],
  //                     question_uuid: "question_uuid10",
  //                     question: "LOGIC 2 - FOLLOW UP TASK CLOSE QUESTION 1",
  //                     description: null,
  //                     critical: false,
  //                     formula: null,
  //                     question_type: "time",
  //                     question_sub_type: null,
  //                     question_hint: null,
  //                     order: 2,
  //                     is_required: true,
  //                     require_live: false,
  //                     number_of_file_allowed: null,
  //                     min_value: null,
  //                     max_value: null,
  //                     max_score: null,
  //                     is_logic_question: false,
  //                     is_task_close_question: true,
  //                     is_audit_info_question: false,
  //                     is_other: false,
  //                     form: 69,
  //                     stage: 82,
  //                     audit_info: null,
  //                     audit_group: null,
  //                     parent_question: null,
  //                     sub_questions: [],
  //                     logics: []
  //                 },
  //               ],
  //               title: "LOGIC 2 - Followup title 2",
  //               deadline: 30,
  //               assign_to: "form_submitter",
  //               logic: 4,
  //               assign_form: null,
  //               user: null,
  //               group: null,
  //               form: 69,
  //               stage: 82,
  //               audit_info: null,
  //               audit_group: null,
  //               question: 221,
  //             },
  //           },
  //         ],
  //       },
  //       {
  //         id: 233,
  //         options: [],
  //         question_uuid: "question_uuid13",
  //         question: "Stage 2- Question 2 - location",
  //         description: null,
  //         critical: false,
  //         formula: null,
  //         question_type: "location",
  //         question_sub_type: null,
  //         question_hint: null,
  //         order: 2,
  //         is_required: true,
  //         require_live: false,
  //         number_of_file_allowed: null,
  //         min_value: null,
  //         max_value: null,
  //         max_score: null,
  //         is_logic_question: false,
  //         is_task_close_question: false,
  //         is_audit_info_question: false,
  //         is_other: false,
  //         form: 69,
  //         stage: 82,
  //         audit_info: null,
  //         audit_group: null,
  //         parent_question: null,
  //         sub_questions: [],
  //         logics: [],
  //       },
  //     ],
  //     created_at: "2025-07-14T09:05:12.175126Z",
  //     updated_at: null,
  //     name: "Stage 1",
  //     order: 1,
  //     form: 69,
  //   },
  {
    id: 84,
    questions: [
      {
        id: 236,
        options: [],
        question_uuid: "question_uuid16",
        question: "Stage 3 - Question 1 - title_and_description",
        description: "Question Description",
        critical: false,
        formula: null,
        question_type: "title_and_description",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 84,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 237,
        options: [],
        question_uuid: "question_uuid17",
        question: "Stage 3 - Question 2 - short_answer",
        description: null,
        critical: false,
        formula: null,
        question_type: "short_answer",
        question_sub_type: null,
        question_hint: "Question Hint",
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 84,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 238,
        options: [],
        question_uuid: "question_uuid18",
        question: "Stage 4 - Question 1 - long_answer",
        description: null,
        critical: false,
        formula: null,
        question_type: "long_answer",
        question_sub_type: null,
        question_hint: "Question Hint",
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 85,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 239,
        options: [
          {
            id: 57,
            created_at: "2025-07-14T09:05:12.481822Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 239,
            stage: 85,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 58,
            created_at: "2025-07-14T09:05:12.495199Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 239,
            stage: 85,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 59,
            created_at: "2025-07-14T09:05:12.505451Z",
            updated_at: null,
            option: "Stage 4 - Question 2 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 239,
            stage: 85,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
        ],
        question_uuid: "question_uuid19",
        question: "Stage 4 - Question 2 - multiple_choice",
        description: null,
        critical: false,
        formula: null,
        question_type: "multiple_choice",
        question_sub_type: "text",
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: true,
        form: 69,
        stage: 85,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 240,
        options: [
          {
            id: 60,
            created_at: "2025-07-14T09:05:12.549959Z",
            updated_at: null,
            option: "Stage 5 - Question 1 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 240,
            stage: 86,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 61,
            created_at: "2025-07-14T09:05:12.558683Z",
            updated_at: null,
            option: "Stage 5 - Question 1 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 240,
            stage: 86,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 62,
            created_at: "2025-07-14T09:05:12.569571Z",
            updated_at: null,
            option: "Stage 5 - Question 1 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 240,
            stage: 86,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
        ],
        question_uuid: "question_uuid20",
        question: "Stage 5 - Question 1 - checkboxes",
        description: null,
        critical: false,
        formula: null,
        question_type: "checkboxes",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 86,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 241,
        options: [
          {
            id: 63,
            created_at: "2025-07-14T09:05:12.591135Z",
            updated_at: null,
            option: "Stage 5 - Question 2 - Option 1",
            score: 0,
            failed: false,
            order: 1,
            question: 241,
            stage: 86,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 64,
            created_at: "2025-07-14T09:05:12.601936Z",
            updated_at: null,
            option: "Stage 5 - Question 2 - Option 2",
            score: 0,
            failed: false,
            order: 2,
            question: 241,
            stage: 86,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 65,
            created_at: "2025-07-14T09:05:12.611531Z",
            updated_at: null,
            option: "Stage 5 - Question 2 - Option 3",
            score: 0,
            failed: false,
            order: 3,
            question: 241,
            stage: 86,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
        ],
        question_uuid: "question_uuid21",
        question: "Stage 5 - Question 2 - dropdown",
        description: null,
        critical: false,
        formula: null,
        question_type: "dropdown",
        question_sub_type: "text",
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: true,
        form: 69,
        stage: 86,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 242,
        options: [
          {
            id: 66,
            created_at: "2025-07-14T09:05:12.649844Z",
            updated_at: null,
            option: "start",
            score: 0,
            failed: false,
            order: 1,
            question: 242,
            stage: 87,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
          {
            id: 67,
            created_at: "2025-07-14T09:05:12.659049Z",
            updated_at: null,
            option: "end",
            score: 0,
            failed: false,
            order: 2,
            question: 242,
            stage: 87,
            audit_info: null,
            audit_group: null,
            form: 69,
          },
        ],
        question_uuid: "question_uuid22",
        question: "Stage 6 - Question 1 - linear_scale",
        description: null,
        critical: false,
        formula: null,
        question_type: "linear_scale",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: 1,
        max_value: 10,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 87,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      //need to implement the datetime module
      {
        id: 243,
        options: [],
        question_uuid: "question_uuid23",
        question: "Stage 6 - Question 2 - datetime",
        description: null,
        critical: false,
        formula: null,
        question_type: "datetime",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 87,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 244,
        options: [],
        question_uuid: "question_uuid24",
        question: "Stage 7 - Question 1 - date",
        description: null,
        critical: false,
        formula: null,
        question_type: "date",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 88,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 245,
        options: [],
        question_uuid: "question_uuid25",
        question: "Stage 7 - Question 2 - time",
        description: null,
        critical: false,
        formula: null,
        question_type: "time",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 88,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 246,
        options: [],
        question_uuid: "question_uuid26",
        question: "Stage 8 - Question 1 - signature",
        description: null,
        critical: false,
        formula: null,
        question_type: "signature",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 89,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 247,
        options: [],
        question_uuid: "question_uuid27",
        question: "Stage 8 - Question 2 - upload_image",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_image",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: true,
        number_of_file_allowed: 5,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 89,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 248,
        options: [],
        question_uuid: "question_uuid28",
        question: "Stage 9 - Question 1 - upload_video",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_video",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: true,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 90,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 249,
        options: [],
        question_uuid: "question_uuid29",
        question: "Stage 9 - Question 2 - upload_file",
        description: null,
        critical: false,
        formula: null,
        question_type: "upload_file",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: 3,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 90,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 250,
        options: [],
        question_uuid: "question_uuid30",
        question: "Stage 10 - Question 1 - qr_code",
        description: null,
        critical: false,
        formula: null,
        question_type: "qr_code",
        question_sub_type: null,
        question_hint: "Stage 10 - Question 1 - qr_code - Question Hint",
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 91,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 252,
        options: [],
        question_uuid: "question_uuid32",
        question: "Stage 10 - Question 3 - user",
        description: null,
        critical: false,
        formula: null,
        question_type: "user",
        question_sub_type: null,
        question_hint: null,
        order: 3,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 91,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 234,
        options: [],
        question_uuid: "question_uuid14",
        question: "Stage 2 - Question 1 - division",
        description: null,
        critical: false,
        formula: null,
        question_type: "division",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 83,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 235,
        options: [],
        question_uuid: "question_uuid15",
        question: "Stage 2 - Question 2 - sub_division",
        description: null,
        critical: false,
        formula: null,
        question_type: "sub_division",
        question_sub_type: null,
        question_hint: null,
        order: 2,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 83,
        audit_info: null,
        audit_group: null,
        parent_question: null,
        sub_questions: [],
        logics: [],
      },
      {
        id: 222,
        options: [],
        question_uuid: "question_uuid2",
        question: "Stage 1 - Table Child Question 1 - location",
        description: null,
        critical: false,
        formula: null,
        question_type: "location",
        question_sub_type: null,
        question_hint: null,
        order: 1,
        is_required: true,
        require_live: false,
        number_of_file_allowed: null,
        min_value: null,
        max_value: null,
        max_score: null,
        is_logic_question: false,
        is_task_close_question: false,
        is_audit_info_question: false,
        is_other: false,
        form: 69,
        stage: 82,
        audit_info: null,
        audit_group: null,
        parent_question: 221,
        sub_questions: [],
        logics: [],
      },
    ],
    created_at: "2025-07-14T09:05:12.420924Z",
    updated_at: null,
    name: "Stage 3",
    order: 3,
    form: 69,
  },
  //   {
  //     id: 91,
  //     questions: [
  //     //   {
  //     //     id: 251,
  //     //     options: [],
  //     //     question_uuid: "question_uuid31",
  //     //     question: "Stage 10 - Question 2 - formula",
  //     //     description: null,
  //     //     critical: false,
  //     //     formula: "SUM(asdasd+asdasd)*asdsd",
  //     //     question_type: "formula",
  //     //     question_sub_type: null,
  //     //     question_hint: null,
  //     //     order: 2,
  //     //     is_required: true,
  //     //     require_live: false,
  //     //     number_of_file_allowed: null,
  //     //     min_value: null,
  //     //     max_value: null,
  //     //     max_score: null,
  //     //     is_logic_question: false,
  //     //     is_task_close_question: false,
  //     //     is_audit_info_question: false,
  //     //     is_other: false,
  //     //     form: 69,
  //     //     stage: 91,
  //     //     audit_info: null,
  //     //     audit_group: null,
  //     //     parent_question: null,
  //     //     sub_questions: [],
  //     //     logics: [],
  //     //   },

  //     ],
  //     created_at: "2025-07-14T09:05:12.759924Z",
  //     updated_at: null,
  //     name: "Stage 10",
  //     order: 10,
  //     form: 69,
  //   },
];
